#cloud-config
users:
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Zugehörigkeit zu Benutzergruppen
    home: /home/ubuntu # Verzeichnis des Benutzers
    shell: /bin/bash # Standard-Shell für den Benutzer
    ssh_authorized_keys: # SSH-Schlüssel für den Benutzer
     ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTQRWoS7SNJRhTB5WIKIxbEBvI/CPpCe0yjk/aHAK0xjN4UrZL1gxQMrnEH2fpOJEBbVa0ALHVEWQmL0s19+sh2I5Mw/PrQWM/zwFfhH0cNLT++pq4qM6rZDWJ5xd01hlyy9dzIj7OVhtpp2vMdgwsuTtcc2XwLp6ybaP2S67+12pdT2ZvcRLn5auaTxMgSYszPnpqx5lnzajEAObpewckNxcsKQbpiJptCT2roXTgstZf3p2o0f6Nil6smrJQ0s69Bj2kncHIpGzPAilOB6xSVgAQcYNCvn9wk2KT+gP6+UC4bMVTisLfjfQPikvU/jg4Zh2OxSiZ3z+VxNJj/7d1 aws-key
ssh_pwauth: false # SSH-Passwort-Authentifizierung deaktivieren
disable_root: false # Root-Benutzer deaktivieren
package_update: true # Paketaktualisierung durchführen
packages: # Installierte Pakete
  - curl
  - wget
