#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTQRWoS7SNJRhTB5WIKIxbEBvI/CPpCe0yjk/aHAK0xjN4UrZL1gxQMrnEH2fpOJEBbVa0ALHVEWQmL0s19+sh2I5Mw/PrQWM/zwFfhH0cNLT++pq4qM6rZDWJ5xd01hlyy9dzIj7OVhtpp2vMdgwsuTtcc2XwLp6ybaP2S67+12pdT2ZvcRLn5auaTxMgSYszPnpqx5lnzajEAObpewckNxcsKQbpiJptCT2roXTgstZf3p2o0f6Nil6smrJQ0s69Bj2kncHIpGzPAilOB6xSVgAQcYNCvn9wk2KT+gP6+UC4bMVTisLfjfQPikvU/jg4Zh2OxSiZ3z+VxNJj/7d1 aws-key
    ssh_pwauth: false
    disable_root: false
package_update: true
packages:
  - apache2
  - curl
  - wget
  - php
  - libapache2-mod-php
  - php-mysql
  - adminer

# Run Commands
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2

# Write Files
write_files:
  - content: |
      <?php
      $servername = "172.31.2.0";
      $username = "admin";
      $password = "password";
      $dbname = "mysql";
      // Create connection
      $conn = new mysqli($servername, $username, $password, $dbname);
      // Check connection
      if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
      }
      $sql = "SELECT Host, User FROM mysql.user;";
      $result = $conn->query($sql);
      while ($row = $result->fetch_assoc()) {
        echo ($row["Host"] . " / " . $row["User"] . "<br />");
      }
    path: /var/www/html/db.php
    permissions: "0644"
    owner: root:root

  - content: |
      <?php
      phpinfo();
    path: /var/www/html/info.php
    permissions: "0644"
    owner: root:root